name: test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dev:
    environment: development
    runs-on: ubuntu-latest

    steps:
    - name: List Environments from GitHub Settings
      run: |
        echo ${{ vars.NAMESPACE }}
        echo ${{ github.event_name }}

  test:
    needs: dev
    environment: test
    runs-on: ubuntu-latest

    steps:
    - name: List Environments from GitHub Settings
      run: echo ${{ vars.NAMESPACE }}

