name: test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Print
      run: |
          echo "Environment Name: ${{ github.event.deployment.environment }}"
