name: test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    environment: development
    runs-on: ubuntu-latest

    steps:
    - name: List Environments from GitHub Settings
      run: echo ${{ vars.NAMESPACE }}

  test2:
    environment: test
    runs-on: ubuntu-latest

    steps:
    - name: List Environments from GitHub Settings
      run: echo ${{ vars.NAMESPACE }}

